formatting:
  MaximumLineLength:
    active: false
style:
  MaxLineLength:
    active: true
    maxLineLength: 150
  UnusedPrivateMember:
    excludes: "**/*Test.kt, **/test/**"
complexity:
  LongMethod:
    active: true
    excludes: "**/*Test.kt, **/test/**"
  LongParameterList:
    functionThreshold: 8
